version: "3"
services:
    nginx:
        image: "nginx:alpine"
        ports:
            - "80:80"
            - "443:443"
        working_dir: /www
        volumes:
            - "${WORKSPACE_PATH_HOST}:/www"
            - "./nginx/log:/var/log/nginx"
            - "./nginx/cert:/etc/nginx/cert"
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        environment:
            TZ: "${TZ}"
        restart: always
        networks:
            - backend
    php:
        build:
            context: ./php
            args:
                TZ: "${TZ}"
        volumes:
            - "${WORKSPACE_PATH_HOST}:/www"
            - "./php/log:/var/log/php"
            - "./php/php.ini:/usr/local/etc/php/php.ini"
            - "./php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        restart: always
        networks:
            - backend
    mysql:
        image: "mysql:8.0"
        ports:
            - "3306:3306"
        environment:
            TZ: "${TZ}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        volumes:
            - "./mysql/log:/var/log/mysql"
            - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
            - "./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
        entrypoint: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
        restart: always
        networks:
            - backend
    redis:
        image: "redis:alpine"
        command: >
                --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - "${DATA_PATH_HOST}/redis:/data"
        restart: always
        networks:
            - backend
networks:
    backend:
        driver: bridge
